services:
  app:
    build: .
    volumes:
      - app_data:/opt/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aprenda_tech
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql

networks:
    default:
        driver: bridge

volumes:
    mysql_data:
    app_data: {}