application:
  security:
    jwt:
      secret: 51a5339157f8ad50b6d77600e02df6c47c12e6ee8826aa02e5eac2ac3b0231e0
      expiration-in-minutes: 1440 # 24 hours

spring:
  application:
    name: aprenda-tech
  datasource:
    url: jdbc:mysql://localhost:3306/aprenda_tech
    username: mysql
    password: mysql
